name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - '*'
    - '!status'
    - '!feedback'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # job to run autograding
  grade:
    name: Autograding
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template || github.event_name == 'workflow_dispatch' }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: install pip dependencies
        run: python -m pip install pandas matplotlib ipython nbconvert

      - name: configure matplotlib
        run: |
          mkdir -p ~/.config/matplotlib
          echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc

      - name: convert notebook to script
        run: jupyter nbconvert --to script assignment.ipynb

      - run: ls -l

      - name: Comment out get_ipython lines
        run: sed -i 's/get_ipython/# get_ipython/g' assignment.py

      - name: run converted python script
        run: python assignment.py

      # run grading
      # add id to step so outputs can be referenced
      - uses: markpatterson27/autograding@dev-step-summary-release
        name: "** Grading and Feedback **"
        id: autograde
        # continue-on-error: true

    outputs:
      grading-score: ${{ steps.autograde.outputs.Points }}

  # job to build activity status icons
  build-activity-icons:
    name: Build Activity Icons
    runs-on: ubuntu-latest
    if: always() && ${{ !github.event.repository.is_template || github.event_name == 'workflow_dispatch' }}
    needs: grade
    steps:
      # need to checkout whole repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # switch to status branch
      - run: git checkout status || git checkout -b status

      # make dir for activity status icons
      - name: make icons dir
        run: mkdir -p .github/activity-icons

      # create points bar
      - name: points bar
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ needs.grade.outputs.grading-score }}
          path: '.github/activity-icons/points-bar.svg'

      # commit and push activity icons if statuses have changed
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/activity-icons'
          git commit -m "Add/Update activity icons" || exit 0
          git push origin status
